# Generated by Django 3.2 on 2021-04-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210424_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='name',
            field=models.CharField(default='test', max_length=1024, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='policy',
            name='max_length',
            field=models.IntegerField(verbose_name='Maximum length'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='min_length',
            field=models.IntegerField(verbose_name='Minimal length'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='status',
            field=models.BooleanField(verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='storage_time',
            field=models.IntegerField(verbose_name='Storage time'),
        ),
    ]
