# Generated by Django 3.2 on 2021-04-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210424_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='storage_time',
            field=models.IntegerField(help_text='Specify storage time in days', verbose_name='Storage time'),
        ),
    ]
