# Generated by Django 3.2 on 2021-04-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_policy_storage_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='storage_time',
            field=models.IntegerField(verbose_name='Storage time'),
        ),
    ]
