# Generated by Django 3.2 on 2021-05-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_account_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='status',
            field=models.BooleanField(blank=True, default=False, verbose_name='Status'),
        ),
    ]
