# Generated by Django 3.2 on 2021-05-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_policy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Status'),
        ),
    ]
